# Use the official Nginx image as a parent image
FROM nginx:stable-alpine

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the configuration file from the current directory to the container
COPY nginx.conf /etc/nginx/conf.d

# Expose port 80 and 443
EXPOSE 80 443

# Start Nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]

