version: "3.8"

services:
  app:
    build: .
    command: gunicorn tripproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    expose:
      - 8000

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - /etc/letsencrypt:/etc/nginx/certs  # Обновленный путь
    ports:
      - "80:80"
      - "443:443"  # Открываем порт 443 для HTTPS
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email afedin.gis2014@gmail.com -d wherefly.online -d www.wherefly.online --agree-tos --no-eff-email

volumes:
  certbot-etc:
  certbot-var:
