version: "3.8"

services:
  app:
    build: .
    command: gunicorn tripproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    expose:
      - 8000

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx_dev.conf:/etc/nginx/conf.d/default.conf  # Изменение здесь
      - ./staticfiles:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - app

